name: Build and Publish Image

on:
  pull_request:
    branches:
      - development
  push:
    branches: [development, staging]
  release:
    types: ["published"]

jobs:
  build-and-publish:
    name: Build and Publish
    uses: cmu-sei/Crucible-Github-Actions/.github/workflows/docker-build.yaml@docker-v1.0
    with:
      imageName: cmusei/caster-api
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
